/** @type {import('next').NextConfig} */
const { launchRedirects } = require('./config/launch-redirects.cjs');

// Public base for site media held in Supabase Storage. Derived from the same
// env var the app already uses, so it follows the project rather than being a
// second place to keep a URL in sync.
const SUPABASE_PUBLIC_MEDIA = `${
  process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://tednluwflfhxyucgwigh.supabase.co'
}/storage/v1/object/public/site-media`;

const nextConfig = {
  // Data-heavy routes (/projects/[slug], /ecosystem, /empathy-ledger, /art/*,
  // /sitemap) fetch EL/Supabase at build-time static generation and were blowing
  // the default 60s per-page cap, failing the whole production deploy. Raise the
  // cap so slow-but-finite fetches complete and the build stays fully static.
  // If a fetch ever truly hangs past this, switch those routes to runtime/ISR.
  staticPageGenerationTimeout: 180,
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "uploads-ssl.webflow.com",
      },
      {
        protocol: "https",
        hostname: "uploads.webflow.com",
      },
      {
        protocol: "https",
        hostname: "assets.website-files.com",
      },
      {
        protocol: "https",
        hostname: "cdn.prod.website-files.com",
      },
      {
        protocol: "https",
        hostname: "tednluwflfhxyucgwigh.supabase.co",
      },
      {
        protocol: "https",
        hostname: "yvnuayzslukamizrlhwb.supabase.co",
      },
      {
        protocol: "https",
        hostname: "uaxhjzqrdotoahjnxmbj.supabase.co",
      },
      {
        protocol: "https",
        hostname: "d1d3n03t5zntha.cloudfront.net",
      },
      {
        protocol: "https",
        hostname: "www.empathyledger.com",
      },
    ],
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  async redirects() {
    return [
      ...launchRedirects,
      // Field videos are served from Supabase Storage rather than the repo.
      //
      // They are 226 MB across 35 files, which git carries into every clone
      // forever and handles badly. Twenty-two of them were never committed at
      // all, so production answered 404 for the hero video on several field
      // pages while the other thirteen worked.
      //
      // A redirect rather than a path rewrite in the source: seventeen files
      // reference /media/field-videos/, and two of them are generated by
      // `npm run sync:el-*`, so any edit to those would be overwritten on the
      // next build. Leaving the paths alone keeps the sync honest.
      //
      // A redirect rather than a Next rewrite: a rewrite proxies the bytes
      // through the Vercel function and bills the bandwidth twice. A 308 sends
      // the browser straight to Supabase, which is what a CDN is for.
      {
        source: "/media/field-videos/:file",
        destination: `${SUPABASE_PUBLIC_MEDIA}/field-videos/:file`,
        permanent: true,
      },
    ];
  },
  // Exclude admin-wiki subdirectory (separate Next.js app)
  pageExtensions: ['tsx', 'ts', 'jsx', 'js'],
  webpack: (config, { isServer }) => {
    config.watchOptions = {
      ...config.watchOptions,
      ignored: ['**/admin-wiki/**', '**/node_modules/**'],
    };
    return config;
  },
};

module.exports = nextConfig;
