#!/usr/bin/env node
// Writes src/brand/tokens.css from src/brand/brand.json, the one home for the brand in code.
// npm run brand:css. The test in src/brand/brand.test.ts fails if the two drift apart.
// The variable names are the ones the Pencil file uses, so a design and its code read the same.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
export const BRAND_JSON = path.join(here, "..", "src", "brand", "brand.json");
export const TOKENS_CSS = path.join(here, "..", "src", "brand", "tokens.css");

const kebab = (s) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

export function render(brand) {
  const lines = [];
  const c = brand.colors;
  lines.push("/* GENERATED by scripts/brand-css.mjs from src/brand/brand.json. Do not edit: change brand.json, run npm run brand:css. */");
  lines.push("/* Imported only by the Brand v1 pieces preview. These names match the Pencil file; the current site's own --font-display retires with the rebuild. */");
  lines.push(":root,");
  lines.push('[data-surface="paper"] {');
  for (const [k, v] of Object.entries(c)) lines.push(`  --${kebab(k)}: ${v};`);
  lines.push(`  --accent: var(--${brand.accent});`);
  for (const [k, v] of Object.entries(brand.surfaces.paper)) lines.push(`  --${k}: ${v};`);
  // --face-* are set by next/font (src/components/pieces/fonts.ts) on the same element or an ancestor, so the
  // self-hosted faces win; the family name is the fallback where next/font is not in play.
  lines.push(`  --font-display: var(--face-display, "${brand.fonts.display}"), Georgia, serif;`);
  lines.push(`  --font-mono: var(--face-mono, "${brand.fonts.mono}"), ui-monospace, monospace;`);
  lines.push(`  --font-loud: var(--face-loud, "${brand.fonts.loud}"), Impact, sans-serif;`);
  for (const [k, v] of Object.entries(brand.weights)) lines.push(`  --weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(brand.sizes)) lines.push(`  --size-${k}: ${v}px;`);
  brand.space.forEach((v, i) => lines.push(`  --space-${i + 1}: ${v}px;`));
  lines.push(`  --radius: ${brand.radius}px;`);
  // The three moves (brand.motion): arrive, roll, unhitch.
  const m = brand.motion;
  lines.push(`  --ease: ${m.ease};`);
  lines.push(`  --ease-arrive: ${m.arrive.ease};`);
  lines.push(`  --ease-unhitch: ${m.unhitch.ease};`);
  lines.push(`  --arrive-ms: ${m.arrive.durationMs}ms;`);
  lines.push(`  --arrive-stagger-ms: ${m.arrive.staggerMs}ms;`);
  lines.push(`  --roll-ms: ${m.roll.linkMs}ms;`);
  lines.push(`  --spin-ms: ${m.roll.loadingSpinMs}ms;`);
  lines.push(`  --unhitch-ms: ${m.unhitch.driveOffMs}ms;`);
  lines.push("}");
  lines.push("");
  lines.push('[data-surface="ink"] {');
  for (const [k, v] of Object.entries(brand.surfaces.ink)) lines.push(`  --${k}: ${v};`);
  lines.push("}");
  // A look is a sub-brand's own colours (Confessions' dark and gold), scoped to [data-look].
  for (const [name, look] of Object.entries(brand.looks ?? {})) {
    lines.push("");
    lines.push(`[data-look="${name}"] {`);
    for (const [k, v] of Object.entries(look.colors)) lines.push(`  --${look.prefix}-${kebab(k)}: ${v};`);
    lines.push("}");
  }
  return lines.join("\n") + "\n";
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const brand = JSON.parse(readFileSync(BRAND_JSON, "utf8"));
  writeFileSync(TOKENS_CSS, render(brand));
  console.log("wrote src/brand/tokens.css");
}
