#!/bin/bash

# ACT Documentation Reorganization - Phase 3
# Move files from root to organized docs/ structure

set -e  # Exit on error

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║    ACT Documentation Reorganization - Phase 3              ║"
echo "║    Organizing Files by Category                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

cd "$(dirname "$0")/.."

# Function to move file if it exists
move_if_exists() {
    if [ -f "$1" ]; then
        mv "$1" "$2"
        echo "  ✓ $1 → $2"
    fi
}

echo "📁 Quick Starts..."
move_if_exists "QUICKSTART.md" "docs/quick-starts/quickstart.md"
move_if_exists "QUICK_START.md" "docs/quick-starts/quick-start.md"
move_if_exists "START_HERE.md" "docs/quick-starts/start-here.md"
move_if_exists "QUICK_REFERENCE.md" "docs/quick-starts/quick-reference.md"
move_if_exists "README_STARTUP.md" "docs/quick-starts/startup.md"
move_if_exists "DEPLOY_NOW.md" "docs/quick-starts/deploy-now.md"
move_if_exists "ENV_QUICK_START.md" "docs/quick-starts/env-setup.md"
move_if_exists "GMAIL_OAUTH_SETUP.md" "docs/quick-starts/gmail-oauth-setup.md"
move_if_exists "FIX_GMAIL_AUTH.md" "docs/quick-starts/fix-gmail-auth.md"
move_if_exists "QUICK_START_GHL.md" "docs/quick-starts/ghl-quick-start.md"
move_if_exists "QUICK_START_GHL_LC_EMAIL.md" "docs/quick-starts/ghl-lc-email.md"
move_if_exists "NAS_QUICK_SETUP.md" "docs/quick-starts/nas-setup.md"

echo ""
echo "🏗️ Architecture..."
move_if_exists "ARCHITECTURE.md" "docs/architecture/overview.md"
move_if_exists "ACT_ECOSYSTEM_ARCHITECTURE.md" "docs/architecture/act-ecosystem.md"
move_if_exists "ACT_COMPLETE_SYSTEM.md" "docs/architecture/complete-system.md"
move_if_exists "ACT_PEOPLE_INTELLIGENCE_ARCHITECTURE.md" "docs/architecture/people-intelligence.md"
move_if_exists "SUPABASE_GHL_INTEGRATION_ARCHITECTURE.md" "docs/architecture/supabase-ghl-integration.md"
move_if_exists "KNOWLEDGE_SYSTEM_DESIGN.md" "docs/architecture/knowledge-system.md"
move_if_exists "DATABASE_SCHEMA.md" "docs/architecture/database-schema.md"
move_if_exists "API_DESIGN.md" "docs/architecture/api-design.md"
move_if_exists "MULTI_CODEBASE_SKILLS_ARCHITECTURE.md" "docs/architecture/multi-codebase-skills.md"
move_if_exists "CODEBASE_STRUCTURE.md" "docs/architecture/codebase-structure.md"

echo ""
echo "✨ Features..."
move_if_exists "LIVING_WIKI_OVERVIEW.md" "docs/features/knowledge-base/overview.md"
move_if_exists "LIVING_WIKI.md" "docs/features/knowledge-base/living-wiki.md"
move_if_exists "KNOWLEDGE_BASE.md" "docs/features/knowledge-base/knowledge-base.md"
move_if_exists "LIVING_WIKI_RESEARCH_IMPROVEMENTS.md" "docs/features/knowledge-base/research-improvements.md"
move_if_exists "ADMIN_WIKI_ENHANCEMENTS.md" "docs/features/knowledge-base/admin-enhancements.md"
move_if_exists "AUTO_APPROVAL.md" "docs/features/knowledge-base/auto-approval.md"
move_if_exists "REVIEW_QUEUE.md" "docs/features/knowledge-base/review-queue.md"
move_if_exists "EMBEDDINGS.md" "docs/features/knowledge-base/embeddings.md"
move_if_exists "DASHBOARD.md" "docs/features/dashboard/overview.md"
move_if_exists "DASHBOARD_IMPLEMENTATION_GUIDE.md" "docs/features/dashboard/implementation-guide.md"
move_if_exists "MEDIA_GALLERY.md" "docs/features/media-gallery/overview.md"
move_if_exists "MEDIA_GALLERY_SETUP.md" "docs/features/media-gallery/setup.md"
move_if_exists "STORY_IMPACT_TRACKING.md" "docs/features/story-impact/overview.md"
move_if_exists "STORY_BASED_IMPACT_IMPLEMENTATION.md" "docs/features/story-impact/implementation.md"
move_if_exists "PROJECT_ENRICHMENT.md" "docs/features/project-enrichment/overview.md"
move_if_exists "ACT_PROJECT_ENRICHMENT_SETUP.md" "docs/features/project-enrichment/setup.md"
move_if_exists "ENGAGEMENT_SYSTEM_COMPLETE.md" "docs/features/engagement-system.md"
move_if_exists "CONTENT_ENGAGEMENT_GUIDE.md" "docs/features/content-engagement.md"

echo ""
echo "🔌 Integrations..."
# GHL
move_if_exists "GHL_INTEGRATION.md" "docs/integrations/ghl/overview.md"
move_if_exists "GHL_SETUP_GUIDE.md" "docs/integrations/ghl/setup-guide.md"
move_if_exists "GHL_SETUP_CHECKLIST.md" "docs/integrations/ghl/setup-checklist.md"
move_if_exists "GHL_IMPLEMENTATION_CHECKLIST.md" "docs/integrations/ghl/implementation-checklist.md"
move_if_exists "GHL_IMPLEMENTATION_STATUS.md" "docs/integrations/ghl/implementation-status.md"
move_if_exists "GHL_INTEGRATION_PROGRESS.md" "docs/integrations/ghl/integration-progress.md"
move_if_exists "GHL_WEBHOOKS.md" "docs/integrations/ghl/webhooks.md"
move_if_exists "GHL_WEBHOOK_SETUP_GUIDE.md" "docs/integrations/ghl/webhook-setup-guide.md"
move_if_exists "GHL_WORKFLOWS.md" "docs/integrations/ghl/workflows.md"
move_if_exists "GHL_PIPELINE_STRATEGY.md" "docs/integrations/ghl/pipeline-strategy.md"
move_if_exists "GHL_AGENCY_LEVEL_GUIDE.md" "docs/integrations/ghl/agency-level-guide.md"
move_if_exists "GHL_SUBACCOUNT_STRATEGY.md" "docs/integrations/ghl/subaccount-strategy.md"
move_if_exists "GHL_ACCOUNT_DIAGNOSTIC.md" "docs/integrations/ghl/account-diagnostic.md"
move_if_exists "GHL_MIGRATION_DECISION_GUIDE.md" "docs/integrations/ghl/migration-decision-guide.md"
move_if_exists "GHL_CONTACT_SYNC_SUMMARY.md" "docs/integrations/ghl/contact-sync-summary.md"
move_if_exists "GHL_CROSS_ACCOUNT_CONTACT_STRATEGY.md" "docs/integrations/ghl/cross-account-contact-strategy.md"
move_if_exists "GHL_LC_EMAIL_INTEGRATION_SUMMARY.md" "docs/integrations/ghl/lc-email-integration-summary.md"
move_if_exists "GHL_LC_EMAIL_SETUP.md" "docs/integrations/ghl/lc-email-setup.md"
move_if_exists "EMAIL_DOMAIN_STRATEGY.md" "docs/integrations/ghl/email-domain-strategy.md"
move_if_exists "EMAIL_DOMAIN_STRATEGY_EXISTING.md" "docs/integrations/ghl/email-domain-strategy-existing.md"
move_if_exists "EMAIL_STRATEGY_GHL_NATIVE.md" "docs/integrations/ghl/email-strategy-ghl-native.md"
# Notion
move_if_exists "NOTION_INTEGRATION.md" "docs/integrations/notion/overview.md"
move_if_exists "NOTION_SCANNER.md" "docs/integrations/notion/scanner.md"
move_if_exists "NOTION_SETUP_INSTRUCTIONS.md" "docs/integrations/notion/setup.md"
move_if_exists "NOTION_ACCESS_SUMMARY.md" "docs/integrations/notion/access-summary.md"
# Gmail
move_if_exists "GMAIL_INTEGRATION.md" "docs/integrations/gmail/overview.md"
move_if_exists "GMAIL_SCANNER.md" "docs/integrations/gmail/scanner.md"
move_if_exists "GMAIL_SCANNER_SETUP.md" "docs/integrations/gmail/scanner-setup.md"
# OpenAI
move_if_exists "OPENAI_INTEGRATION.md" "docs/integrations/openai/overview.md"
move_if_exists "OPENAI_SETUP.md" "docs/integrations/openai/setup.md"
# Supabase
move_if_exists "SUPABASE_SETUP.md" "docs/integrations/supabase/setup.md"
# Empathy Ledger
move_if_exists "EMPATHY_LEDGER_INTEGRATION.md" "docs/integrations/empathy-ledger/overview.md"
move_if_exists "EMPATHY_LEDGER_SETUP_GUIDE.md" "docs/integrations/empathy-ledger/setup-guide.md"
move_if_exists "EMPATHY_LEDGER_IMPACT_INTEGRATION.md" "docs/integrations/empathy-ledger/impact-integration.md"

echo ""
echo "🛠️ Development..."
move_if_exists "DEVELOPMENT.md" "docs/development/getting-started.md"
move_if_exists "DEV_HUB_SETUP.md" "docs/development/dev-hub-setup.md"
move_if_exists "VSCODE_SETUP.md" "docs/development/vscode-setup.md"
move_if_exists "CONTRIBUTING.md" "docs/development/contributing.md"
move_if_exists "CODE_STYLE.md" "docs/development/code-style.md"
move_if_exists "TESTING.md" "docs/development/testing.md"
move_if_exists "DEBUGGING.md" "docs/development/debugging.md"
move_if_exists "ENV_AUDIT_AND_MANAGEMENT.md" "docs/development/env-management.md"
move_if_exists "CROSS_CODEBASE_BEST_PRACTICES.md" "docs/development/cross-codebase-best-practices.md"

echo ""
echo "⚙️ Operations..."
move_if_exists "DEPLOYMENT.md" "docs/operations/deployment.md"
move_if_exists "MONITORING.md" "docs/operations/monitoring.md"
move_if_exists "TROUBLESHOOTING.md" "docs/operations/troubleshooting.md"
move_if_exists "MAINTENANCE.md" "docs/operations/maintenance.md"
move_if_exists "MULTI_REPO_MANAGEMENT.md" "docs/operations/multi-repo-management.md"
move_if_exists "MULTI_REPO_QUICK_REFERENCE.md" "docs/operations/multi-repo-quick-reference.md"
move_if_exists "MULTI_REPO_CHANGELOG.md" "docs/operations/multi-repo-changelog.md"
move_if_exists "SYNOLOGY_SETUP_GUIDE.md" "docs/operations/synology-setup.md"

echo ""
echo "🎯 Strategy..."
move_if_exists "ROADMAP.md" "docs/strategy/roadmap.md"
move_if_exists "ACT-ECOSYSTEM-ROADMAP.md" "docs/strategy/act-ecosystem-roadmap.md"
move_if_exists "NEXT_STEPS_ROADMAP.md" "docs/strategy/next-steps-roadmap.md"
move_if_exists "ACT_MASTER_PLAN.md" "docs/strategy/master-plan.md"
move_if_exists "ACT_ECOSYSTEM_VISUAL_STRATEGY.md" "docs/strategy/visual-strategy.md"
move_if_exists "VISION.md" "docs/strategy/vision.md"
move_if_exists "PRIORITIES.md" "docs/strategy/priorities.md"
move_if_exists "BACKLOG.md" "docs/strategy/backlog.md"

echo ""
echo "🎨 Brand..."
move_if_exists "BRAND_GUIDE.md" "docs/brand/brand-guide.md"
move_if_exists "VOICE_AND_TONE.md" "docs/brand/voice-and-tone.md"
move_if_exists "MESSAGING.md" "docs/brand/messaging.md"
move_if_exists "VISUAL_IDENTITY.md" "docs/brand/visual-identity.md"
move_if_exists "DRAFT_BIOS.md" "docs/brand/content-drafts/draft-bios.md"
move_if_exists "DRAFT_MISSION_AND_ABOUT.md" "docs/brand/content-drafts/draft-mission-and-about.md"

echo ""
echo "📊 Projects..."
move_if_exists "ACT_ECOSYSTEM.md" "docs/projects/act-ecosystem.md"
move_if_exists "README_ECOSYSTEM.md" "docs/projects/ecosystem-readme.md"
move_if_exists "EMPATHY_LEDGER.md" "docs/projects/empathy-ledger/overview.md"
move_if_exists "JUSTICEHUB.md" "docs/projects/justicehub/overview.md"
move_if_exists "HARVEST.md" "docs/projects/harvest/overview.md"
move_if_exists "HARVEST_TENANT_UPDATE.md" "docs/projects/harvest/tenant-update.md"
move_if_exists "BCV.md" "docs/projects/bcv/overview.md"

echo ""
echo "📋 Standards..."
move_if_exists "NAMING_CONVENTIONS.md" "docs/standards/naming-conventions.md"
move_if_exists "FILE_STRUCTURE.md" "docs/standards/file-structure.md"
move_if_exists "COMMIT_MESSAGES.md" "docs/standards/commit-messages.md"
move_if_exists "UNIFIED_PROJECT_STANDARDS.md" "docs/standards/unified-project-standards.md"
move_if_exists "SKILL_PROPOSAL_GHL_ADVISOR.md" "docs/standards/skill-proposal-ghl-advisor.md"

echo ""
echo "📖 Examples..."
move_if_exists "EXAMPLES.md" "docs/examples/overview.md"
move_if_exists "SAMPLE_WORKFLOWS.md" "docs/examples/workflows.md"
move_if_exists "INTEGRATION_EXAMPLE.md" "docs/examples/integration-example.md"

echo ""
echo "🏗️ Infrastructure..."
move_if_exists "INFRASTRUCTURE.md" "docs/infrastructure/overview.md"
move_if_exists "HOSTING.md" "docs/infrastructure/hosting.md"
move_if_exists "SECURITY.md" "docs/infrastructure/security.md"
move_if_exists "MAGIC_LINK_SETUP.md" "docs/infrastructure/magic-link-setup.md"

echo ""
echo "📦 Archive - Status & Implementation Summaries..."
move_if_exists "MULTI_PROJECT_SETUP_COMPLETE.md" "docs/archive/2024-12/"
move_if_exists "SYSTEM_SETUP_COMPLETE.md" "docs/archive/2024-12/"
move_if_exists "SYSTEM_STATUS_COMPLETE.md" "docs/archive/2024-12/"
move_if_exists "IMPLEMENTATION_SUMMARY.md" "docs/archive/2024-12/"
move_if_exists "OPTIMIZATION_SUMMARY.md" "docs/archive/2024-12/"
move_if_exists "QUICK_WINS_IMPLEMENTATION.md" "docs/archive/2024-12/"
move_if_exists "WIKI_SCAN_SUCCESS.md" "docs/archive/2024-12/"
move_if_exists "STARTUP_IMPROVEMENTS.md" "docs/archive/2024-12/"
move_if_exists "PROGRESS-UPDATE.md" "docs/archive/2024-12/"

echo ""
echo "📦 Archive - Meta Documentation..."
move_if_exists "DOCUMENTATION_REORGANIZATION_PLAN.md" "docs/archive/2024-12/"
move_if_exists "DOCUMENTATION_SUMMARY.md" "docs/archive/2024-12/"

echo ""
echo "📊 Summary..."
echo ""
find docs -type f -name "*.md" | wc -l | xargs echo "Total docs in organized structure:"
ls -1 *.md 2>/dev/null | wc -l | xargs echo "Remaining in root:"

echo ""
echo "✅ Phase 3 complete!"
echo ""
echo "Next step: Review remaining root files and consolidate duplicates"
echo ""
